before_script:
  - apt-get update -qq && apt-get install -y -qq python-pip
  - pip install platformio
  - platformio lib --global install ArduinoJson
  
linux:
  script:
    - platformio ci --lib="." --board=nodemcuv2 examples/sensor/sensor.ino
    - platformio ci --lib="." --board=nodemcuv2 examples/startHere/startHere.ino
